In [140]:
import numpy as np
import math

In [141]:
grid = np.zeros((20,4,4))

In [142]:
ds = [[-1,0], [1, 0], [0,-1], [0,1]]

In [143]:
def iterative_policy_evaluation(k, current_state):
    next_state = []
    (x, y) = (current_state[0], current_state[1])
    next_value = 0
    
    for i in range(0,4):        
        state = [x + ds[i][0], y + ds[i][1]]
                
        if (state[0] < 0 or state[0] > 3):
            state[0] = x
        if (state[1] < 0 or state[1] > 3):
            state[1] = y
            
        next_value += (-1 + grid[k-1][state[0]][state[1]])        
    
    grid[k][x][y] = round(next_value/4, 1)    

In [144]:
for k in range(1,len(grid)):
    for i in range(0, 4):
        for j in range(0, 4):
            if(i == 0 and j == 0):
                continue
            elif(i == 3 and j == 3):
                continue

            iterative_policy_evaluation(k, [i,j])

In [145]:
print(grid)

[[[  0.    0.    0.    0. ]
  [  0.    0.    0.    0. ]
  [  0.    0.    0.    0. ]
  [  0.    0.    0.    0. ]]

 [[  0.   -1.   -1.   -1. ]
  [ -1.   -1.   -1.   -1. ]
  [ -1.   -1.   -1.   -1. ]
  [ -1.   -1.   -1.    0. ]]

 [[  0.   -1.8  -2.   -2. ]
  [ -1.8  -2.   -2.   -2. ]
  [ -2.   -2.   -2.   -1.8]
  [ -2.   -2.   -1.8   0. ]]

 [[  0.   -2.4  -3.   -3. ]
  [ -2.4  -2.9  -3.   -3. ]
  [ -3.   -3.   -2.9  -2.4]
  [ -3.   -3.   -2.4   0. ]]

 [[  0.   -3.1  -3.8  -4. ]
  [ -3.1  -3.7  -4.   -3.8]
  [ -3.8  -4.   -3.7  -3.1]
  [ -4.   -3.8  -3.1   0. ]]

 [[  0.   -3.6  -4.7  -4.9]
  [ -3.6  -4.6  -4.8  -4.7]
  [ -4.7  -4.8  -4.6  -3.6]
  [ -4.9  -4.7  -3.6   0. ]]

 [[  0.   -4.2  -5.5  -5.8]
  [ -4.2  -5.2  -5.6  -5.5]
  [ -5.5  -5.6  -5.2  -4.2]
  [ -5.8  -5.5  -4.2   0. ]]

 [[  0.   -4.7  -6.3  -6.6]
  [ -4.7  -5.9  -6.4  -6.3]
  [ -6.3  -6.4  -5.9  -4.7]
  [ -6.6  -6.3  -4.7   0. ]]

 [[  0.   -5.2  -7.   -7.4]
  [ -5.2  -6.6  -7.1  -7. ]
  [ -7.   -7.1  -6.6  -5.2]
  [ 